# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
    -   repo: https://github.com/pre-commit/mirrors-clang-format
        rev: 'v16.0.3'  # Use the sha / tag you want to point at
        hooks:
        -   id: clang-format
