== *libCertifier()*

* Written in C for embedded devices.
* Small binary size (less than 100 KB) that is ideal for embedded systems.
* Tested on Arm (Raspberry Pi, Android, xCam, i.MX, Ambarella, iOS), as well as x86_64 (Ubuntu, MacOS, x86_32 (Ubuntu).
* C library and command-line executable.
* Generates ECC key pairs, fetches x509 certificate from xPKI and renews certificates.
* See xref:open_source_dependencies.adoc[*Open Source Dependencies*]

*Integration Methods*

* xref:cli_usage.adoc[Command line executable (CLI)]
* xref:api_usage.adoc[Shared Library (API]) 

== *Overview*

libCertifier() communicates with the following back-end service.  TLS is used.

'''

|===
| *Service* | *Description* | *Mandatory*

| Certifier
| Communicates with the xPKI Certificate Authority and is used to generate the x509 certificate.  +
Certifier also handles all necessary authentication.  Please refer to xref:anatomy_of_https_certifier_call.adoc[Anatomy of an HTTPS call to Certifier page] to better understand the interaction between client (libCertifier) and server (Certifier).  
| Yes
|===

*Project structure*

The table below describes the files in this project -

|===
| *Folder/File Name* | *Description*

| CMakeLists.txt
| CMake file for creating builds

| xref:../README.adoc[README.adoc]
| Readme file

| include
| *public* source header files

| internal_headers
| *private* source header files

| libcertifier-cert.crt
| Certificate trust store used by libcurl for HTTPS calls

| xref:configuration.adoc[libcertifier.cfg.sample]
| Sample libCertifier configuration file

| resources
| Device Attestation Certificate

| src
| Source files

| tests
| Unit tests, as well as functional tests (shell scripts)
|===

== *Build*

libCertifier was written with xref:portability.adoc[portability] in mind, and has been tested on both MacOS and Linux systems. If you have difficulty building libCertifier, please don't hesitate to seek support through our support forums or contact us directly!

Please read the xref:build.adoc[*build section*] for more information on how to build libCertifier.

*Binary Size*

libCertifier is less than 100KB in size (stripped).

libcertifier.so is around 95KB.

certifierUtil is around 3KB.

== *Memory Consumption (Heap) ignoring deallocations*

See xref:memory_consumption_by_function.adoc[*Memory Consumption*]

== *Error Codes*

See xref:error_codes.adoc[*Error Codes*]

== *Configuration*

See xref:configuration.adoc[*libcertifier.cfg*]

== *Logging*

See xref:logging.adoc[*Logging*]
