xref:libcertifier.adoc[*Back to Manual*]

============
libCertifier Matter Plugin Demonstration Usage
=====

*Build*

To build libcertifier along example applications of Matter Commissioning Flow you have to type the following commands:

----
git clone git@github.com:Comcast/libcertifier.git
cd libcertifier
source build_matter_plugin_build.sh
----

Having run this, two target executables will be created. Check how to use them in the following Sections.

*Commissionee Usage (certifier-all-clusters-app)*

This is the first executable/target that should be run. This application will act as a device in a Matter network ready to be commissioned.

----
./certifier-all-clusters-app --vendor-id 65524 --product-id 4353
----

*Comissioner Usage (certifier-tool)*

Once the Commissionee application is running, `certifier-tool` shall be run with the following parameters:

----
./certifier-tool pairing onnetwork 0x12 20202021 --paa-trust-store-path ../matter_plugin/matter-sdk/credentials/development/paa-root-certs
./certifier-tool onoff toggle 0x12 1 --paa-trust-store-path ../matter_plugin/matter-sdk/credentials/development/paa-root-certs
----

This application will interact with the cloud PKI and issue certificates both to the Commissioner (during initialization) and Commissionee (during Matter Commissioning Flow) applications.

The second line of the command above will be used to test a Toggle command to a lighting device.
