xref:libcertifier.adoc[*Back to Manual*]

============
libCertifier Matter Plugin Demonstration Usage
=====

*Build*

To build libcertifier along example applications of Matter Commissioning Flow you have to type the following commands:

----
git clone git@github.com:Comcast/libcertifier.git
cd libcertifier
source build_matter_plugin.sh
----

Having run this, two target executables will be created. Check how to use them in the following Sections.

*Commissionee Usage (certifier-all-clusters-app)*

This is the first executable/target that should be run. This application will act as a device in a Matter network ready to be commissioned.

----
./certifier-all-clusters-app --vendor-id 65524 --product-id 4353 --dac dac-commissionee.p12 --dac-password changeit
----

*Commissioner Usage (certifier-tool)*

Commissioner will interact with the cloud PKI and retrieve Matter NOC certificates for both to the Commissioner (during initialization) and Commissionee (during Matter Commissioning Flow), using either X.509 or SAT authentication.

Once the Commissionee application is running, run `certifier-tool` with the following parameters:

X.509 authentication:

----
./certifier-tool pairing onnetwork-certifier 0x12 20202021 --paa-trust-store-path ../matter_sdk/credentials/development/paa-root-certs --dac-filepath dac-commissioner.p12 --dac-password changeit
----

SAT authentication:

----
./certifier-tool pairing onnetwork-certifier 0x12 20202021 --paa-trust-store-path ../matter_sdk/credentials/production/paa-root-certs --sat 1 --sat-token <token>
----

Instead of passing SAT as a command line parameter, it can be added to the `libcertifier.cfg` file as indicated below:

----
"libcertifier.sat.token": "<token>",
----

Then, run `certifier-tool` with the following parameters:

----
./certifier-tool pairing onnetwork-certifier 0x12 20202021 --paa-trust-store-path ../matter_sdk/credentials/production/paa-root-certs --sat 1
----

After successfully commissioning the device, execute the following to send a Toggle command to a lighting device:

----
./certifier-tool onoff toggle 0x12 1 --paa-trust-store-path ../matter_sdk/credentials/development/paa-root-certs --dac-filepath dac-commissioner.p12 --dac-password changeit
----
